name: preprocessing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.17
  - pandas=2.0.3
  - pip=23.2.1
  - pyarrow=11.0.0
  - fastparquet=2023.7.0
  - protobuf=3.20.3
  - pip:
      - wandb==0.10.21
